<a href="https://colab.research.google.com/github/camulro/Aprendizaje-II/blob/sesi%C3%B3n2/CC_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##CONVOLUTION TESTS

In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
input_1d = torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype = torch.float)
input_2d = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]],dtype = torch.float)
input_2d_img = torch.tensor([[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]],
                             [[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]],
                             [[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]]],dtype = torch.float)

In [4]:
print(input_1d.shape)
print(input_2d.shape)
print(input_2d_img.shape)

torch.Size([10])
torch.Size([2, 5])
torch.Size([3, 3, 10])


##CNN 1D PARA ENTRADAS 1D

Preparar entrada para convolución.

In [6]:
input_1d = input_1d.unsqueeze(0).unsqueeze(0)
input_1d.shape

torch.Size([1, 1, 10])

CAPA CNN 1D

In [7]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=1,kernel_size=3,stride=1)
print("cnn1d_1: \n")
print(cnn1d_1(input_1d).shape, "\n")
print(cnn1d_1(input_1d))

cnn1d_1: 

torch.Size([1, 1, 8]) 

tensor([[[1.2144, 2.1657, 3.1169, 4.0681, 5.0193, 5.9706, 6.9218, 7.8730]]],
       grad_fn=<SqueezeBackward1>)


Aumentar stride:

In [9]:
cnn1d_2 = nn.Conv1d(in_channels=1,out_channels=1,kernel_size=3,stride=2) #salto del kernel de dos en dos posiciones, tendras la mitad de resultados
print("cnn1d_2: \n")
print(cnn1d_2(input_1d).shape, "\n")
print(cnn1d_2(input_1d))

cnn1d_2: 

torch.Size([1, 1, 4]) 

tensor([[[-0.9797, -1.7096, -2.4394, -3.1692]]], grad_fn=<SqueezeBackward1>)


Cambiar kernel size:

In [10]:
cnn1d_3 = nn.Conv1d(in_channels=1,out_channels=1,kernel_size=2,stride=1)
print("cnn1d_3: \n")
print(cnn1d_3(input_1d).shape, "\n")
print(cnn1d_3(input_1d))
#longitud de salida de la convolución de 9 resultados, hace 9 desplazamientos

cnn1d_3: 

torch.Size([1, 1, 9]) 

tensor([[[0.2546, 0.5621, 0.8695, 1.1770, 1.4845, 1.7919, 2.0994, 2.4068,
          2.7143]]], grad_fn=<SqueezeBackward1>)


Cambiar out_channels:

In [11]:
cnn1d_4 = nn.Conv1d(in_channels=1,out_channels=5,kernel_size=3,stride=1) #añadimos canales a la salida(segundo elemnto del tensor)
print("cnn1d_4: \n")
print(cnn1d_4(input_1d).shape, "\n")
print(cnn1d_4(input_1d))

cnn1d_4: 

torch.Size([1, 5, 8]) 

tensor([[[-2.0122, -2.8041, -3.5960, -4.3879, -5.1798, -5.9717, -6.7635,
          -7.5554],
         [ 1.7706,  2.1082,  2.4459,  2.7836,  3.1213,  3.4589,  3.7966,
           4.1343],
         [ 1.6418,  1.9140,  2.1862,  2.4584,  2.7306,  3.0028,  3.2750,
           3.5472],
         [-1.1448, -1.5364, -1.9279, -2.3194, -2.7109, -3.1024, -3.4939,
          -3.8854],
         [-0.6060, -0.9088, -1.2116, -1.5144, -1.8172, -2.1200, -2.4228,
          -2.7256]]], grad_fn=<SqueezeBackward1>)


Añadir padding:

In [13]:
cnn1d_5 = nn.Conv1d(in_channels=1,out_channels=1,kernel_size=3,stride=1,padding=1) #compensamos la muestra que queda fuera de la convolución en los extremos del vector
print("cnn1d_5: \n")
print(cnn1d_5(input_1d).shape, "\n")
print(cnn1d_5(input_1d))
#preserva la dimensión original

cnn1d_5: 

torch.Size([1, 1, 10]) 

tensor([[[0.3199, 1.0354, 1.7510, 2.4665, 3.1820, 3.8976, 4.6131, 5.3287,
          6.0442, 1.6648]]], grad_fn=<SqueezeBackward1>)


##CNN 1D PARA ENTRADAS 2D##

Preparar entrada

In [14]:
input_2d = input_2d.unsqueeze(0)
input_2d.shape

torch.Size([1, 2, 5])

In [15]:
cnn1d_6 = nn.Conv1d(in_channels=2, out_channels=1,kernel_size=3,stride=1)
print("cnn1d_6: \n")
print(cnn1d_6(input_2d).shape, "\n")
print(cnn1d_6(input_2d))

cnn1d_6: 

torch.Size([1, 1, 3]) 

tensor([[[1.0969, 1.6052, 2.1135]]], grad_fn=<SqueezeBackward1>)


Aumentar stride:

In [16]:
cnn1d_7 = nn.Conv1d(in_channels=2, out_channels=1,kernel_size=3,stride=2) #solo tendrá dos posiciones solapadas, 2 valores en la convolución
print("cnn1d_7: \n")
print(cnn1d_7(input_2d).shape, "\n")
print(cnn1d_7(input_2d))

cnn1d_7: 

torch.Size([1, 1, 2]) 

tensor([[[-5.7256, -7.7826]]], grad_fn=<SqueezeBackward1>)


Cambiar kernel size:

In [17]:
cnn1d_8 = nn.Conv1d(in_channels=2, out_channels=1,kernel_size=2,stride=1) #4 resultados porque recorre una señal de tamaño 5
print("cnn1d_8: \n")
print(cnn1d_8(input_2d).shape, "\n")
print(cnn1d_8(input_2d))

cnn1d_8: 

torch.Size([1, 1, 4]) 

tensor([[[4.2932, 5.0858, 5.8785, 6.6711]]], grad_fn=<SqueezeBackward1>)


Cambiar out_channels:

In [18]:
cnn1d_9 = nn.Conv1d(in_channels=2, out_channels=5,kernel_size=3,stride=1) #5 canales de tamaño 3x1
print("cnn1d_9: \n")
print(cnn1d_9(input_2d).shape, "\n")
print(cnn1d_9(input_2d))

cnn1d_9: 

torch.Size([1, 5, 3]) 

tensor([[[ 3.2362,  3.6449,  4.0535],
         [-0.6075, -0.4713, -0.3351],
         [ 2.6466,  3.4375,  4.2284],
         [-2.7023, -3.2734, -3.8444],
         [-0.2923, -0.1227,  0.0469]]], grad_fn=<SqueezeBackward1>)


Añadir padding:

In [21]:
cnn1d_10 = nn.Conv1d(in_channels=2, out_channels=1,kernel_size=3,stride=1,padding=1)#5 productos y sumas al añadir 0s en los extremos
print(cnn1d_10(input_2d).shape, "\n")
print(cnn1d_10(input_2d))

torch.Size([1, 1, 5]) 

tensor([[[-2.2269, -0.6175, -0.7934, -0.9693, -1.9775]]],
       grad_fn=<SqueezeBackward1>)
